name: ci cd example

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to prod server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete --exclude='.env'"
          SOURCE: "./"
          EXCLUDE: ".git,.github,.gitignore,node_modules"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/cicd_example/"
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SCRIPT_BEFORE: |
            curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -
            sudo apt-get install -y nodejs
            curl -L https://www.npmjs.com/install.sh | sh
            npm install -g npx
            npm install -g pm2
            ls -al
          SCRIPT_AFTER: |
            pm2 restart all
            if [ -f ecosystem.config.js ]; then pm2 reload ecosystem.config.js; fi
            ls -al
            echo $RSYNC_STDOUT